### ISSUE TITLE
Monitor Commands Issue

### ISSUE THREAD

**Issue by ghost** [zedwick/BungeeChatFilter#2]
They will monitor all commands.
I use the /tpa fuck command.I will be kicked out

```
#Commands - The list of commands that the plugin will monitor
Commands:
    - msg
AntiSpam: true
Minimum-Chat-Delay: 1500
rules:
  swearfilter2:
    regex:
    - .*fuck.*
    actions:
      deny: true
      kick: 'fuck'
```
