### ISSUE TITLE
Failing to parse rules after "!permission.permission"

### ISSUE THREAD

**Issue by hankur** [zedwick/BungeeChatFilter#3]
First of all, thank you for bringing this wonderful plugin back to life.

There seems to be a problem with filtering rules that are positioned after rule that contains permission starting with "!" sign. Default config is a great example of this:

``` yaml
  CommandShortcut2:
    regex: /shop
    actions:
      scommand: /warp shop
      deny: true
  CreateCommand:
    regex: /broadcast
    permission: '!bungeefilter.broadcast'
    actions:
      alert: '&5[Broadcast]&a{player}&f:{arguments}'
      deny: true
  CreateCommand2:
    regex: (/url)|(/website)
    actions:
      message: '&l&6[Check it out]&3 This server''s website is &6www.minecraftserver.com'
      deny: true
```

The command before CreateCommand works fine _(submits "/warp shop" to the Spigot server)_, but the command after it is not filtered _("/url" is sent directly to Spigot, without denying or sending a message)_. But if the player has the required permission _(in this case "bungeefilter.broadcast")_, even rules following it work as they're supposed to.

It caused me a bit of a headache, since some command aliases were "randomly" not working for majority of players. Luckily I found the cause of this and hope it will get fixed soon.

Using BungeeChatFilter v1.6.1 and BungeeCord build 1180.
