### ISSUE TITLE
Commands as action not working

### ISSUE THREAD

**Issue by hankur** [zedwick/BungeeChatFilter#4]
None of the command types (p-, c-, scommand) seem to be working, the plugin just skips over them. No errors, no commands executed.

Using BungeeChatFilter v1.6.1 and BungeeCord build 1180.

**Comment by zedwick** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QKJYtKqa&#x2F;10-commands-as-action-not-working"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Commands as action not working</a>

**Comment by zedwick** [comment]
Sorry for the lack of reply, could you provide your config complete with examples of them not working?

**Comment by hankur** [comment]
Better late than never ;)

Well, even the default config's command aliases (/shop for example) don't work. When I type in "/shop", it's passed straight to Spigot server.

**Comment by zedwick** [comment]
That sounds like #3 ... Which version of BungeeChatFilter are you running?

So it is not even cancelling the event (deny: true)?
It passes "/shop" to the spigot server, rather than passing "/warp shop" to the spigot server?

**Comment by hankur** [comment]
Tested it with the latest version of BCF (1.6.4). Bungeecord build 1190.

No, it's not cancelling:

```
[14:35:57] [Server thread/INFO]: Projekt4769 issued server command: /shop
```

As far as I've tested, the plugin just skips "pcommand". In addition, "scommand" completely breaks the rule.

**Comment by hankur** [comment]
So I thought I would "bump" this issue with some extra information. Using BCF 1.6.4 and Bungeecord #1228.

I created some simple rules with real commands (and added them to the monitored commands list):
```
rules:
  pc:
    regex: /pc
    actions:
      deny: true
      pcommand: '/message'
  sc:
    regex: /sc
    actions:
      deny: true
      scommand: '/msg'
  cc:
    regex: /cc
    actions:
      deny: true
      ccommand: '/m'
```
Rule "pc" and "cc" did nothing, while "sc" worked perfectly.

Next, I removed "deny: true" and tested again:
```
rules:
  pc:
    regex: /pc
    actions:
      pcommand: '/message'
  cc:
    regex: /cc
    actions:
      ccommand: '/m'
```

This time, both of them were passed straight to the Spigot server, Bungeecord console remained empty:
```
[19:23:19 INFO]: Projekt4769 issued server command: /pc
[19:23:23 INFO]: Projekt4769 issued server command: /cc

```

**Comment by zedwick** [comment]
I've gotten them working in 1.6.4:

```
Commands:
- cc
- pc

rules:
  cc:
    regex: /cc
    actions:
      ccommand: glist
      deny: true
  pc:
    regex: /pc
    actions:
      pcommand: glist
      deny: true
```

scommand is just sending a chat message as the player, so you need to include the leading / to make them work as commands, however pcommand and ccommand are sending specified commands as the player/console respectively, so cannot have a leading / as it is looking for the name of the command first. pcommand and ccommand also require the command to be a valid, registered command on the proxy server; if the command does not exist then it will just silently fail.

I can see the documentation in the config is misleading for these actions, so I'll fix that.
